version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableChecksOnVariables
            - disableChecksOnConstants
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
