name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    env:
      UPX_VERSION: 4.2.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run base workflow
        uses: ./.github/actions/base
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: bash ./tools/dependencies.sh

      - name: Build A2S
        run: bash ./tools/build.sh cli/a2s a2s-cli

      - name: Build A3SB
        run: bash ./tools/build.sh cli/a3sb a3sb-cli

      - name: Extract changelog
        id: changelog
        run: awk -f ./tools/release_notes.awk ./CHANGELOG.md > release.md

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: release.md
          artifacts: ./build/*
